library(scales)
library(randomcoloR)

c1 <- distinctColorPalette(k = 20, seed=12)
c2 <- randomColor(count=20, hue = 'red', luminosity = 'light', seed=2020)

message('Distinct colors are repeatable:')
print(c1)
message('The seed number in randomcolorR does not interrupt the global randomness')
print(rnorm(10))
message('Random colors are repeatable:')
print(c2)
message('The seed number in randomcolorR does not interrupt the global randomness')
print(rnorm(10))

pdf("~/repeatable.pdf", width = 7, onefile = T)
plot(1)
scales::show_col(c1)
scales::show_col(c2)
dev.off()
